#HW tutorial/book
#3.7 Statistical transformations
#https://r4ds.had.co.nz/data-visualisation.html
#https://r4ds.had.co.nz/data-visualisation.html#statistical-transformations

#3 Data visualisation
rm(list=ls())
ls()
getwd()
setwd("")
library(tidyverse)
library(ggplot2)
library(plotly)
ggplot2::diamonds
?diamonds

#cut = quality of the cut (Fair, Good, Very Good, Premium, Ideal)

#The following chart displays 
#the total number of diamonds in the diamonds dataset, grouped by cut

#geom_bar()
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut))

#stat_count()
ggplot(data = diamonds) + 
  stat_count(mapping = aes(x = cut))

# reasons you might need to use a stat explicitly:
# 1) You might want to override the default stat.
# stat = "count" (default) --> stat = "identity"
# stat = "count" --> the height of the bar is generated by counting rows
# stat = "identity" --> the height of the bar is already present in the data

demo <- tribble(
  ~cut,         ~freq,
  "Fair",       1610,
  "Good",       4906,
  "Very Good",  12082,
  "Premium",    13791,
  "Ideal",      21551
)

ggplot(data = demo) +
  geom_bar(mapping = aes(x = cut, y = freq), stat = "identity")

# reasons you might need to use a stat explicitly:
# 2) You might want to override the default mapping from transformed variables to aesthetics
# For example, you might want to display a bar chart of proportion, rather than count:

ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, y = ..prop.., group = 1))

# reasons you might need to use a stat explicitly:
# 3) You might want to draw greater attention to the statistical transformation in your code.

?diamonds
diamonds
#cut = quality of the cut (Fair, Good, Very Good, Premium, Ideal)
#depth = total depth percentage = z / mean(x, y) = 2 * z / (x + y) (43–79)

ggplot(data = diamonds) + 
  geom_point(mapping = aes(x = cut, y = depth))
    
    ggplot(data = diamonds) + 
  stat_summary(
    mapping = aes(x = cut, y = depth),
    fun.ymin = min,
    fun.ymax = max,
    fun.y = median
  )

